const data={process:[['01','Discovery',['Meeting client','Understanding vision','Moodboard creation'],'Focus'],['02','Planning',['Storyboard','Shot list','Location scouting'],'Map'],['03','Production',['Filming','Photography','Drone','Lighting'],'Shutter'],['04','Editing',['Color grading','Retouching','Sound design'],'Timeline'],['05','Delivery',['Cloud Gallery','Instagram Reels','Films','Luxury Album'],'Launch']],films:[['The Vow After Rain','Wedding Film','https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=80'],['Night Market Pulse','Street Film','https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80'],['Maison Lumiere','Commercial','https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80'],['Above the Coast','Drone','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80']],photos:['Portrait','Wedding','Street','Travel','Fashion','Commercial','Drone','Night'].map((c,i)=>({cat:c,img:['https://images.unsplash.com/photo-1500648767791-00dcc994a43e','https://images.unsplash.com/photo-1519741497674-611481863552','https://images.unsplash.com/photo-1519501025264-65ba15a82390','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee','https://images.unsplash.com/photo-1509631179647-0177331693ae','https://images.unsplash.com/photo-1497366754035-f200968a6e72','https://images.unsplash.com/photo-1473968512647-3e447244af8f','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429'][i]+'?auto=format&fit=crop&w=900&q=80'})),bts:[['Camera setup','https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1000&q=80'],['Lighting','https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1000&q=80'],['Drone','https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1000&q=80'],['Editing desk','https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=80']],testimonials:[['It felt like a film set, but the photos still felt completely ours.','Aarav and Meera'],['FRAMEVERSE gave our campaign the polish of a luxury launch.','Noor, Founder'],['The final gallery looked like memory with better lighting.','Kabir, Artist']],pricing:[['Portrait','$750',['2 hour session','30 retouched images','Private gallery']],['Wedding','$3,500',['Full day coverage','Highlight film','Luxury album option']],['Commercial','$5,000',['Creative direction','Photo and motion','Usage-ready edits']]]};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
window.addEventListener('load',()=>document.body.classList.add('loaded'));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view'); if(e.target.matches('.stats')) countStats();}}),{threshold:.18});$$('.reveal,.reveal-text,.line-copy,.stats').forEach(e=>io.observe(e));
$('#processTimeline').innerHTML=data.process.map(p=>'<article class="process-card reveal"><div class="num">'+p[0]+'</div><div><h3>'+p[1]+'</h3><p class="eyebrow">'+p[3]+'</p></div><ul>'+p[2].map(x=>'<li>'+x+'</li>').join('')+'</ul><div class="icon-orbit">'+p[3][0]+'</div></article>').join('');$$('.process-card').forEach(e=>io.observe(e));
$('#filmRail').innerHTML=data.films.map(f=>'<article class="film-card tilt-card"><img src="'+f[2]+'" alt="'+f[0]+'"><div><p class="eyebrow">'+f[1]+'</p><h3>'+f[0]+'</h3></div></article>').join('');
const filters=['All',...data.photos.map(p=>p.cat)];$('#filters').innerHTML=filters.map((f,i)=>'<button class="filter '+(i?'':'active')+'" data-filter="'+f+'">'+f+'</button>').join('');function renderPhotos(cat='All'){ $('#masonry').innerHTML=data.photos.concat(data.photos).filter(p=>cat==='All'||p.cat===cat).map((p,i)=>'<button class="photo-card photo-hover" data-img="'+p.img+'"><img src="'+p.img+'" alt="'+p.cat+' photograph"><span>'+p.cat+'</span></button>').join(''); bindPhotos();}renderPhotos();$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPhotos(b.dataset.filter)});
$('#btsTrack').innerHTML=data.bts.map(b=>'<article class="bts-card"><img src="'+b[1]+'" alt="'+b[0]+'"><div><h3>'+b[0]+'</h3></div></article>').join('');$('#testimonialDeck').innerHTML=data.testimonials.map(t=>'<article class="testimonial-card tilt-card"><p>"'+t[0]+'"</p><span>'+t[1]+'</span></article>').join('');$('#pricingGrid').innerHTML=data.pricing.map(p=>'<article class="price-card"><span>'+p[0]+'</span><h3>'+p[0]+'</h3><strong>'+p[1]+'</strong><ul>'+p[2].map(x=>'<li>'+x+'</li>').join('')+'</ul><a class="button ghost" href="#booking">Book Now</a></article>').join('');
const reels=data.photos.map(p=>'<img class="reel" src="'+p.img+'" alt="Instagram reel '+p.cat+'">').join('');$('#instaRail').innerHTML=reels;$('#instaRailClone').innerHTML=reels;
function bindPhotos(){ $$('.photo-card').forEach(card=>card.onclick=()=>{const m=$('#imageModal');$('img',m).src=card.dataset.img;m.classList.add('open');m.setAttribute('aria-hidden','false')}) }$('#closeModal').onclick=()=>{$('#imageModal').classList.remove('open');$('#imageModal').setAttribute('aria-hidden','true')};
$('#showreelBtn').onclick=()=>{$('#showreelModal').classList.add('open');$('#showreelModal').setAttribute('aria-hidden','false')};$('#closeShowreel').onclick=()=>{$('#showreelModal').classList.remove('open');$('#showreelModal').setAttribute('aria-hidden','true')};
let step=0;const steps=$$('.form-step'),stepDots=$$('.steps span');function updateStep(done=false){steps.forEach((s,i)=>s.classList.toggle('active',i===step));stepDots.forEach((d,i)=>d.classList.toggle('active',i<=step));$('#prevStep').style.visibility=step?'visible':'hidden';$('#nextStep').textContent=step===steps.length-1?'Send Request':'Next';if(done)$('#bookingSuccess').classList.add('show')}$('#nextStep').onclick=()=>{if(step<steps.length-1){step++;updateStep()}else updateStep(true)};$('#prevStep').onclick=()=>{step=Math.max(0,step-1);updateStep()};updateStep();
let counted=false;function countStats(){if(counted)return;counted=true;$$('[data-count]').forEach(el=>{const target=+el.dataset.count;let n=0;const timer=setInterval(()=>{n+=Math.ceil(target/42);if(n>=target){n=target;clearInterval(timer)}el.textContent=n},25)})}
const cursor=$('.cursor');window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';document.documentElement.style.setProperty('--mx',e.clientX/window.innerWidth-.5);document.documentElement.style.setProperty('--my',e.clientY/window.innerHeight-.5)});document.addEventListener('mouseover',e=>cursor.classList.toggle('focus',!!e.target.closest('.photo-hover,.photo-card')));$$('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform='translate('+((e.clientX-r.left-r.width/2)*.12)+'px,'+((e.clientY-r.top-r.height/2)*.12)+'px)'}));$$('.magnetic').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''));
const c=$('#particles'),ctx=c.getContext('2d');let particles=[];function resize(){c.width=innerWidth;c.height=innerHeight;particles=Array.from({length:90},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.8+.4,v:Math.random()*.35+.1}))}function anim(){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='rgba(200,169,106,.55)';particles.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=c.height;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(anim)}addEventListener('resize',resize);resize();anim();
